server:
  port: 8051
  servlet:
    context-path: /auth_user

spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  application:
    name: ead-authuser
  #RabbitMQ
  rabbitmq:
    addresses: amqps://ftnvmbsd:xgD3-_1PipNCZo3negu-BmaA9BdAEfjI@shrimp.rmq.cloudamqp.com/ftnvmbsd
  cloud:
    #Openfeign
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: basic
      circuitbreaker:
        enabled: true
  #Datasource
  datasource:
    url: "jdbc:mysql://localhost:3308/ead-async-authuser?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    username: root
    password: P@ssword1756
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      jdbc:
        lob:
          non-contextual-creation: true
    database-platform: org.hibernate.dialect.MySQLDialect
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

logging:
  level:
    com.ead: TRACE
    root: info
    org.springframework.web: debug
    org.hibernate: info

#RestTemplate URI connection between microservices
ead:
  course:
    url: "http://ead-course/courses"
  broker:
    exchange:
      userEvent: ead.userevent

authuser:
  refreshscope:
    name: Ederson de Jesus Santos!

#Circuitbreaker
resilience4j:
  circuitbreaker:
    instances:
      circuit-get-all-courses-by-user:
        register-health-indicator: true
        sliding-window-size: 30
        permitted-number-of-calls-in-half-open-state: 2
        sliding-window-type: TIME_BASED
        minimum-number-of-calls: 2
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 80
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 5s
    instances:
      retry-get-all-courses-by-user:
        base-config: default
#Actuator
management:
  server:
    port: 9049
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - refresh
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    loggers:
      enabled: true
