spring:
  application:
    name: ead-course
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        service-id: ead-config-server
      username: configserver
      password: 'ead123cs'
      authority: 'ADMIN'