server:
  port: 8888

spring:
  application:
    name: ead-config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        #native:
          #search-locations: file:///${user.home}/ead/authuser,  file:///${user.home}/ead/course
        git:
          uri: 'https://github.com/edersonjseder/ead-config-server-repo'
          default-label: main
          username: edersonjseder
          password: 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
  h2:
    console:
      enabled: true
      path: /h2-ui
  datasource:
    url: jdbc:h2:file:./mydb
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

ead:
  config-server:
    username: configserver
    password: 'ead123cs'
    authority: 'ROLE_ADMIN'
  service-registry:
    username: serviceregistry
    password: 'ead123sr'
    authority: 'ROLE_ADMIN'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.service-registry.username}:${ead.service-registry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost
